#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../recipe.sh"

version="6.3.0"
sha512="e85a0dab5195889948a3462189f0e0598d331d3457612e2d3350799dba2e244316d256f8161df5219538eb003e4b5343f989aaa00f96321559063ed8c8f29fd2"

DEPENDENCIES="make xz m4"

recipe_start
export PATH="$OUT/make/bin:$OUT/xz/bin:$OUT/m4/bin:$PATH"
xz -d -c "$(recipe_download "https://ftp.gnu.org/gnu/gmp/gmp-$version.tar.xz" "$sha512")" | tar xf -
cd "./gmp-$version"

./configure --prefix="$OUT/$SCRIPT_NAME"
make -j "$NUM_CPUS"
make -j "$NUM_CPUS" install

rm -rf "$PWD"
recipe_finish
