#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../recipe.sh"

version="3.11"
sha512="f254a1905a08c8173e12fbdd4fd8baed9a200217fba9d7641f0d78e4e002c1f2a621152d67027d9b25f0bb2430898f5233dc70909d8464fd13d7dd9298e65c42"

DEPENDENCIES="make xz"

recipe_start
export PATH="$OUT/make/bin:$OUT/xz/bin:$PATH"
xz -d -c "$(recipe_download "https://ftp.gnu.org/gnu/grep/grep-$version.tar.xz" "$sha512")" | tar xf -
cd "./grep-$version"

./configure --prefix="$OUT/$SCRIPT_NAME" --disable-dependency-tracking --disable-nls --without-libiconv-prefix --without-libintl-prefix
make -j "$NUM_CPUS"
make -j "$NUM_CPUS" install

rm -rf "$PWD"
recipe_finish
