#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../recipe.sh"

version="1.3.1"
sha512="4bab4ef6076f8c5dfdc99d810b51108ced61ea2942ba0c1c932d624360a5473df20d32b300fc76f2ba4aa2a97e1f275c9fd494a1ba9f07c4cb2ad7ceaeb1ae97"

DEPENDENCIES="make gmp mpfr"

recipe_start
export PATH="$OUT/make/bin:$OUT/xz/bin:$PATH"
gzip -d -c "$(recipe_download "https://ftp.gnu.org/gnu/mpc/mpc-$version.tar.gz" "$sha512")" | tar xf -
cd "./mpc-$version"

./configure --prefix="$OUT/$SCRIPT_NAME" --with-gmp="$OUT/gmp" --with-mpfr="$OUT/mpfr" --disable-dependency-tracking
make -j "$NUM_CPUS"
make -j "$NUM_CPUS" install

rm -rf "$PWD"
recipe_finish
