#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../../recipe.sh"

version="1.23.1"
sha512="818eda003e3f7aa15690eedb1ff227a6056b2ce54bf23d45ffe573dc40a914623c5a1358218b59444dcdc483db0503324f0d27091d0ea954412a8b290de5f50a"

DEPENDENCIES="../xz ../python ../meson ../samurai ../pkgconf ../wayland-scanner x86_64-linux-gnu-gcc x86_64-linux-gnu-gcc_libffi"

recipe_start
export PATH="$OUT/xz/bin:$OUT/python/bin:$OUT/meson/bin:$OUT/samurai/bin:$OUT/pkgconf/bin:$PATH"
xz -d -c "$(recipe_download "https://gitlab.freedesktop.org/wayland/wayland/-/releases/$version/downloads/wayland-$version.tar.xz" "$sha512")" | tar xf -
cd "./wayland-$version"

cat >cross.txt <<END
[binaries]
c = '$OUT/x86_64-linux-gnu-gcc/usr/bin/x86_64-x-linux-gnu-gcc'
cpp = ''
ar = '$OUT/x86_64-linux-gnu-gcc/usr/bin/x86_64-x-linux-gnu-ar'
strip = '$OUT/x86_64-linux-gnu-gcc/usr/bin/x86_64-x-linux-gnu-strip'
pkg-config = '$OUT/pkgconf/bin/pkgconf'

[host_machine]
system = 'linux'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[properties]
sys_root = '$OUT/x86_64-linux-gnu-gcc_libffi'
END

export NINJA=samu
meson setup --cross-file ./cross.txt -Dprefix=/usr --buildtype=plain -Dc_args="-ffile-prefix-map=$OUT=." \
-Dpkg_config_path="$OUT/x86_64-linux-gnu-gcc_libffi/usr/lib/pkgconfig" -Dbuild.pkg_config_path="$OUT/wayland-scanner/lib/pkgconfig:$OUT/wayland-scanner/libdata/pkgconfig" \
-Ddocumentation=false -Ddtd_validation=false -Dtests=false -Dscanner=false build

meson compile -j "$NUM_CPUS" -C build
DESTDIR="$OUT/$SCRIPT_NAME" meson install -C build

rm -rf "$PWD"
recipe_finish
