#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../../recipe.sh"

version="xkbcommon-1.8.1"
sha512="3e75dce17aaa042ca3134b6cd1b8c0da570b517420cd51e707087e0250186b122751ec84530b906b53faf0a85cae2696d67c2a8637fd61a35b36b1f9bc96ec2b"

DEPENDENCIES="../xz ../python ../meson ../samurai ../bison x86_64-linux-gnu-gcc"

recipe_start
export PATH="$OUT/xz/bin:$OUT/python/bin:$OUT/meson/bin:$OUT/samurai/bin:$OUT/bison/bin:$PATH"
xz -d -c "$(recipe_git_xz_download "https://github.com/xkbcommon/libxkbcommon.git" "$version" "$sha512")" | tar xf -
cd "./libxkbcommon.git-$version"

cat >cross.txt <<END
[binaries]
c = '$OUT/x86_64-linux-gnu-gcc/usr/bin/x86_64-x-linux-gnu-gcc'
cpp = ''
ar = '$OUT/x86_64-linux-gnu-gcc/usr/bin/x86_64-x-linux-gnu-ar'
strip = '$OUT/x86_64-linux-gnu-gcc/usr/bin/x86_64-x-linux-gnu-strip'
pkg-config = ''

[host_machine]
system = 'linux'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'
END

export NINJA=samu
meson setup --cross-file ./cross.txt -Dprefix=/usr -Dc_args="-ffile-prefix-map=$OUT=." \
-Denable-wayland=false -Denable-x11=false -Denable-xkbregistry=false build

meson compile -j "$NUM_CPUS" -C build
DESTDIR="$OUT/$SCRIPT_NAME" meson install -C build

rm -rf "$PWD"
recipe_finish
