#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../../recipe.sh"

version="0.3.65"
sha512="c2d6c7265902c2dacefcb046ef836ab28c88de602a16c61780ed1ccca60a007516415b93bbd52c5024a89a0d686a7e8dc9e800a5240cb26a861a9a5d17e07f8c"

DEPENDENCIES="../python ../meson ../samurai x86_64-linux-gnu-gcc"

recipe_start
export PATH="$OUT/python/bin:$OUT/meson/bin:$OUT/samurai/bin:$PATH"
gzip -d -c "$(recipe_git_download "https://gitlab.freedesktop.org/pipewire/pipewire.git" "$version" "$sha512")" | tar xf -
cd "./pipewire.git-$version"

cat >cross.txt <<END
[binaries]
c = '$OUT/x86_64-linux-gnu-gcc/usr/bin/x86_64-x-linux-gnu-gcc'
cpp = ''
ar = '$OUT/x86_64-linux-gnu-gcc/usr/bin/x86_64-x-linux-gnu-ar'
strip = '$OUT/x86_64-linux-gnu-gcc/usr/bin/x86_64-x-linux-gnu-strip'
pkg-config = ''

[host_machine]
system = 'linux'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'
END

export NINJA=samu
meson setup --cross-file ./cross.txt -Dprefix=/usr -Dc_args="-ffile-prefix-map=$OUT=." \
-Dauto_features=disabled -Ddbus=disabled -Dexamples=disabled -Dflatpak=disabled \
-Dsession-managers="[]" -Dtests=disabled build
meson compile -j "$NUM_CPUS" -C build
DESTDIR="$OUT/$SCRIPT_NAME" meson install -C build

rm -rf "$PWD"
recipe_finish
