#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../../recipe.sh"

version="0.1.1"
sha512="b4fd3d22bbc61cd7b0bfc70b1cd89bea60d563de0e7716d87e2e1a6ad32d3dec9850396a0692bb1f879b4aa341ceca816e196cb149a89067eb571d498ab7df25"

DEPENDENCIES="../xz ../python ../meson ../samurai ../pkgconf ../wayland-protocols x86_64-linux-gnu-gcc x86_64-linux-gnu-gcc_wayland"

recipe_start
export PATH="$OUT/xz/bin:$OUT/python/bin:$OUT/meson/bin:$OUT/samurai/bin:$OUT/wayland-scanner/bin:$PATH"
xz -d -c "$(recipe_download "https://gitlab.freedesktop.org/-/project/18349/uploads/ee5ef0f2c3a4743e8501a855d61cb397/libdecor-$version.tar.xz" "$sha512")" | tar xf -
cd "./libdecor-$version"

mkdir ./sysroot
cd ./sysroot
(cd "$OUT/wayland-protocols" && tar cf - usr) | tar xf -
(cd "$OUT/x86_64-linux-gnu-gcc_wayland" && tar cf - usr) | tar xf -
(cd "$OUT/x86_64-linux-gnu-gcc_libffi" && tar cf - usr) | tar xf -
cd ..

cat >cross.txt <<END
[binaries]
c = '$OUT/x86_64-linux-gnu-gcc/usr/bin/x86_64-x-linux-gnu-gcc'
cpp = ''
ar = '$OUT/x86_64-linux-gnu-gcc/usr/bin/x86_64-x-linux-gnu-ar'
strip = '$OUT/x86_64-linux-gnu-gcc/usr/bin/x86_64-x-linux-gnu-strip'
pkg-config = '$OUT/pkgconf/bin/pkgconf'

[host_machine]
system = 'linux'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[properties]
sys_root = '$PWD/sysroot'
END

# TODO upstream ability to avoid building plugins
sed -e "s/subdir('plugins')//" ./src/meson.build > ./sed.temp
mv ./sed.temp ./src/meson.build

export NINJA=samu
meson setup --cross-file ./cross.txt -Dprefix=/usr --buildtype=plain -Dc_args="-ffile-prefix-map=$OUT=." \
-Dpkg_config_path="$PWD/sysroot/usr/lib/pkgconfig:$PWD/sysroot/usr/share/pkgconfig" \
-Ddbus=disabled -Ddemo=false build

meson compile -j "$NUM_CPUS" -C build
DESTDIR="$OUT/$SCRIPT_NAME" meson install -C build

rm -rf "$PWD"
recipe_finish
